### ISSUE TITLE
Deprecated selector in `peppermint-syntax\index.less`

### ISSUE THREAD

**Issue by Ares-III** [eshanmind/peppermint-syntax#1]
In `peppermint-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region`

* `atom-text-editor::shadow .variable.other.object.js` => `atom-text-editor.editor .syntax--variable.syntax--other.syntax--object.syntax--js`

* `atom-text-editor::shadow .variable.other.property.js` => `atom-text-editor.editor .syntax--variable.syntax--other.syntax--property.syntax--js`

* `atom-text-editor::shadow .meta.method-call.js > .entity.name.function.js` => `atom-text-editor.editor .syntax--meta.syntax--method-call.syntax--js > .syntax--entity.syntax--name.syntax--function.syntax--js`

* `atom-text-editor::shadow .meta.function-call.js > .entity.name.function.js` => `atom-text-editor.editor .syntax--meta.syntax--function-call.syntax--js > .syntax--entity.syntax--name.syntax--function.syntax--js`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by eshrh** [comment]
honestly, i don't really know how to fix this :(, i just released this theme just for kicks. I'm looking into it, but if you can fix it yourself, i would greatly appreciate it!
